"""Remove unique constraint from stock_transactions

Revision ID: b4df5f3de436
Revises: eee5ca8296e3
Create Date: 2025-07-25 22:16:46.216810

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4df5f3de436"
down_revision: Union[str, None] = "eee5ca8296e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove unique constraint from stock_transactions.stock_symbol
    op.drop_constraint(
        "stock_transactions_stock_symbol_key", "stock_transactions", type_="unique"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add back unique constraint to stock_transactions.stock_symbol
    op.create_unique_constraint(
        "stock_transactions_stock_symbol_key", "stock_transactions", ["stock_symbol"]
    )

    # ### end Alembic commands ###
